apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: play
  namespace: play
spec:
  default:
    timeoutSec: 1800
    connectionDraining:
      drainingTimeoutSec: 1800
    sessionAffinity:
      type: CLIENT_IP
  targetRef:
    group: ""
    kind: Service
    name: play
    namespace: play
# NOTE: Namespace is required or it thinks you mean the "default" namespace
