// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file server/chat/v1/chat.proto (package server.chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BroadcastChatRequest, BroadcastChatResponse, NewChatSessionRequest, NewChatSessionResponse } from "./chat_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.chat.v1.ChatService
 */
export const ChatService = {
  typeName: "server.chat.v1.ChatService",
  methods: {
    /**
     * @generated from rpc server.chat.v1.ChatService.NewChatSession
     */
    newChatSession: {
      name: "NewChatSession",
      I: NewChatSessionRequest,
      O: NewChatSessionResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc server.chat.v1.ChatService.BroadcastChat
     */
    broadcastChat: {
      name: "BroadcastChat",
      I: BroadcastChatRequest,
      O: BroadcastChatResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

