// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file server/poll/v1/poll.proto (package server.poll.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EndVotingEventMessage, EndVotingResponse, GameRoomCreateEventMessage, GameRoomCreateResponse, ParticipantAudienceJoinEventMessage, ParticipantAudienceJoinResponse, ParticipantVoteEventMessage, ParticipantVoteResponse, StartVotingEventMessage, StartVotingResponse, SubscribeRequestMessage, SubscribeResponse } from "./poll_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.poll.v1.PollService
 */
export const PollService = {
  typeName: "server.poll.v1.PollService",
  methods: {
    /**
     * @generated from rpc server.poll.v1.PollService.ParticipantAudienceJoinRequest
     */
    participantAudienceJoinRequest: {
      name: "ParticipantAudienceJoinRequest",
      I: ParticipantAudienceJoinEventMessage,
      O: ParticipantAudienceJoinResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc server.poll.v1.PollService.ParticipantVoteRequest
     */
    participantVoteRequest: {
      name: "ParticipantVoteRequest",
      I: ParticipantVoteEventMessage,
      O: ParticipantVoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.poll.v1.PollService.GameRoomCreateRequest
     */
    gameRoomCreateRequest: {
      name: "GameRoomCreateRequest",
      I: GameRoomCreateEventMessage,
      O: GameRoomCreateResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc server.poll.v1.PollService.StartVotingRequest
     */
    startVotingRequest: {
      name: "StartVotingRequest",
      I: StartVotingEventMessage,
      O: StartVotingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.poll.v1.PollService.EndVotingRequest
     */
    endVotingRequest: {
      name: "EndVotingRequest",
      I: EndVotingEventMessage,
      O: EndVotingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.poll.v1.PollService.SubscribeRequest
     */
    subscribeRequest: {
      name: "SubscribeRequest",
      I: SubscribeRequestMessage,
      O: SubscribeResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

